---
# tasks file for php

- name: Install PHP-FPM
  apt:
    name: php8.1-fpm 
    update_cache: yes

- name: Config PHP-FPM
  lineinfile:
    path: /etc/php/8.1/fpm/pool.d/www.conf
    search_string: "listen ="
    line: "listen = {{ nginx_ip }}:9000"

- name: Start process
  systemd:
    name: php8.1-fpm
    state: restart