---
- hosts: test
  become: yes
  gather_facts: false
   
  tasks: 
  
  - name: Create user
    user:
      name: user1
      shell: /bin/bash
  - name: install
    apt:
      name: curl
      state: present

  - name: Copy key
    copy:
      src: "~/.ssh/id_rsa-enc.pub"
      dst: "/home/user1/.ssh/authorized_keys"
