---
- hosts: localhost 
  
  tasks: 
    
  - name: Install Nginx
    apt:
      name: nginx
      update_cache: yes
      
  - name: STOP service nginx, if not started
    command: /etc/init.d/nginx stop

  - name: Index
    template:
      src: ../template/nginx.j2
      dest: /var/www/html/index.html

  - name: START service nginx, if not started
    command: /etc/init.d/nginx start