---
- hosts: test

  tasks:

  - name: Change resolve.cfg
    lineinfile: 
      path: /etc/resolv.conf
      insertbefore: 'nameserver 8.8.8.8'
      line: 'nameserver {{ ansible_facts.all_ipv4_addresses.0 }}'
