---
- hosts: localhost
  vars: 
    phpV: '8.1'
  tasks:

  - name: Relocation DocumentRoot
    lineinfile:
      path: /etc/nginx/sites-available/default
      regexp: \sroot /var/www/html;
      line: "root /opt/nginx/ansible;"
 